### ISSUE TITLE
许多类似这样的布局是否可以调整的更好阅读些？

### ISSUE THREAD

**Issue by doggy8088** [qiangmzsx/Software-Engineering-at-Google#23]
这样的 Markdown 布局好像不太方便阅读

![image](https://user-images.githubusercontent.com/88981/175787050-ee86f512-37f1-4074-8ac8-5dcf5e0697a9.png)

**Comment by qiangmzsx** [comment]
> 这样的 Markdown 布局好像不太方便阅读
> 
> ![image](https://user-images.githubusercontent.com/88981/175787050-ee86f512-37f1-4074-8ac8-5dcf5e0697a9.png)

这是注解部分，我们本意是与正文区分开来，如果有更好的布局方式，我们可以一起尝试看看。

**Comment by doggy8088** [comment]
建议可以这样写

---

事實上，很難設想任何可以被認為是現代軟體工程的任務不立即採用VCS。鑑於你瞭解版本控制的價值和需要，你現在可能會問你需要什麼型別的版本控制。

> 3	Indeed, I’ve given several public talks that use “adoption of version control” as the canonical example of how the norms of software engineering can and do evolve over time. In my experience, in the 1990s, version control was pretty well understood as a best practice but not universally followed. In the early 2000s, it was still common to encounter professional groups that didn’t use it. Today, the use of tools like Git seems ubiquitous even among college students working on personal projects. Some of this rise in adoption is likely due to better user experience in the tools (nobody wants to go back to RCS), but the role of experience and changing norms is significant.
>
> 3 事實上，我曾多次公開演講，以 "版本控制的採用 "為例，說明軟體工程的規範是如何隨著時間的推移而演變的。根據我的經驗，在20世紀90年代，版本控制被理解為一種最佳實踐，但沒有得到普遍遵守。在21世紀初，不使用版本控制的專業團體仍然很常見。今天，即使在從事個人專案的大學生中，像Git這樣的工具的使用似乎也是無處不在的。這種採用率的上升可能是由於在工具中更好的使用者體驗（沒有人願意回到RCS），但經驗和不斷變化的規範的作用也很重要。

**Comment by qiangmzsx** [comment]
> 建议可以这样写，用 `> ` 达成缩排效果！
> 
> 事实上，很难设想任何可以被认为是现代软件工程的任务不立即采用VCS。鉴于你了解版本控制的价值和需要，你现在可能会问你需要什么类型的版本控制。
> 
> > 3	Indeed, I’ve given several public talks that use “adoption of version control” as the canonical example of how the norms of software engineering can and do evolve over time. In my experience, in the 1990s, version control was pretty well understood as a best practice but not universally followed. In the early 2000s, it was still common to encounter professional groups that didn’t use it. Today, the use of tools like Git seems ubiquitous even among college students working on personal projects. Some of this rise in adoption is likely due to better user experience in the tools (nobody wants to go back to RCS), but the role of experience and changing norms is significant.
> > 3 事实上，我曾多次公开演讲，以 "版本控制的采用 "为例，说明软件工程的规范是如何随着时间的推移而演变的。根据我的经验，在20世纪90年代，版本控制被理解为一种最佳实践，但没有得到普遍遵守。在21世纪初，不使用版本控制的专业团体仍然很常见。今天，即使在从事个人项目的大学生中，像Git这样的工具的使用似乎也是无处不在的。这种采用率的上升可能是由于在工具中更好的用户体验（没有人愿意回到RCS），但经验和不断变化的规范的作用也很重要。

第一章已经被修改为引用方式，可以对照一下效果。

**Comment by doggy8088** [comment]
这样很棒，谢谢

**Comment by doggy8088** [comment]
我今天看到 [Footnotes now supported in Markdown fields](https://github.blog/changelog/2021-09-30-footnotes-now-supported-in-markdown-fields/) 这份文档，我觉得这语法虽然不支持在 Markdown 文档中使用，只能用在 Issue 与 Gist 里面，但我觉得这样的格式蛮好的，更清楚的标示他是一个注脚。

---

Here is a simple footnote[^1]. With some additional text after it.

[^1]: My reference.

**Comment by qiangmzsx** [comment]
> 我今天看到 [Footnotes now supported in Markdown fields](https://github.blog/changelog/2021-09-30-footnotes-now-supported-in-markdown-fields/) 这份文档，我觉得这语法虽然不支持在 Markdown 文档中使用，只能用在 Issue 与 Gist 里面，但我觉得这样的格式蛮好的，更清楚的标示他是一个注脚。
> 
> Here is a simple footnote[1](#user-content-fn-1-a698df437a9c258824208f26df28b478). With some additional text after it.
> 
> ## Footnotes
> 1. My reference. [↩](#user-content-fnref-1-a698df437a9c258824208f26df28b478)

在https://github.com/qiangmzsx/Software-Engineering-at-Google/blob/main/zh-cn/Chapter-21_Dependency_Management/Chapter-21_Dependency_Management.md#user-content-fn-3-65093b4d140a2ca10c285f3aadcc0f0e  我们已经使用了注释链接方式。我们可以把两者结合使用。

**Comment by doggy8088** [comment]
我调整了新的格式，你看一下这样行不行？

https://github.com/qiangmzsx/Software-Engineering-at-Google/pull/27

**Comment by qiangmzsx** [comment]
> 我把 Chapter 1 调整了新的格式，你看一下这样行不行？
> 
> #27

我觉得挺好的，后续全部改为这样的方式吧！

**Comment by qiangmzsx** [comment]
> 这样的 Markdown 布局好像不太方便阅读
> 
> ![image](https://user-images.githubusercontent.com/88981/175787050-ee86f512-37f1-4074-8ac8-5dcf5e0697a9.png)

已经全部修改完毕了，可以关闭了

**Comment by qiangmzsx** [comment]
> @qiangmzsx 有全改吗？我好像还看到旧的布局格式？
> 
> https://qiangmzsx.github.io/Software-Engineering-at-Google/#/zh-cn/Chapter-6_Leading_at_Scale/Chapter-6_Leading_at_Scale
> 
> ![image](https://user-images.githubusercontent.com/88981/176695834-8478223f-55e4-41e2-84b1-68e4b5ff033d.png)
> 
> 等等，这应该不是「注脚」的部分，不过我觉得应该也要改成 `> ` 的布局方式才好看。

原文也没有使用引用的方式：
![image](https://user-images.githubusercontent.com/4846144/176795976-0a5fb263-2f9a-48aa-933c-3f15b1cf0726.png)

**Comment by doggy8088** [comment]
其实「注脚」的布局应该跟「引用」的布局不太一样。但是 GitHub 的 Markdown 文档不支持「注脚」样式，所以我们才退而求其次的使用「引用」的方式来呈现，呈现上也不会觉得奇怪。

你的截图就是确确实实的「引用」样式，我认为 Markdown 也可以用这种格式来呈现，这种方式才不会让文章出现 horizontal scrollbar，阅读上也比较舒适。

**Comment by doggy8088** [comment]
我觉得蛮舒服的，哈哈 😅

无论如何，我觉得比出现 horizontal scrollbar 舒服多了！

**Comment by qiangmzsx** [comment]
> 我觉得蛮舒服的 😄
> 
> 无论如何，我觉得比出现 horizontal scrollbar 舒服多了！

你可以提交PR修改看看效果
