### ISSUE TITLE
非常好的项目！如果能单独读英文或单独读中文就好了。

### ISSUE THREAD

**Issue by vzchn** [qiangmzsx/Software-Engineering-at-Google#31]
非常好的项目！如果能单独读英文或单独读中文就好了。
实际上很少有人会混着读吧？

**Comment by qiangmzsx** [comment]
> 非常好的项目！如果能单独读英文或单独读中文就好了。 实际上很少有人会混着读吧？

我们的本意不是让大家混合着阅读，因为翻译者本身能力水平有限，出现翻译不准确的时候，可以让读者对照一下因为阅读，更能准确理解内容。更重要的是读者可以进行修正原本的翻译，提交更加准确的翻译。

**Comment by vzchn** [comment]
好。我正在读，的确发现了一些可能需要改进的地方。

**Comment by qiangmzsx** [comment]
> 好。我正在读，的确发现了一些可能需要改进的地方。

欢迎提交PR
