### ISSUE TITLE
是否能够构建单独的中文版本

### ISSUE THREAD

**Issue by cliuxinxin** [qiangmzsx/Software-Engineering-at-Google#42]
这样看起来比较快一点

**Comment by qiangmzsx** [comment]
> 这样看起来比较快一点

等大家对书的内容进行校验完成了，修订少了，可以尝试分离为两份份：中英、中文。

**Comment by cliuxinxin** [comment]
快猛糙的搞了下，脚本和成品都放上去了，request pull确实不会，官方可参考。。。。。https://github.com/cliuxinxin/Software-Engineering-at-Google/blob/main/zh/Preface.md

**Comment by qiangmzsx** [comment]
> 快猛糙的搞了下，脚本和成品都放上去了，request pull确实不会，官方可参考。。。。。https://github.com/cliuxinxin/Software-Engineering-at-Google/blob/main/zh/Preface.md

大赞，等内容稳定了，欢迎提交PR

**Comment by wuqingwei** [comment]
> 快猛糙的搞了下，脚本和成品都放上去了，request pull确实不会，官方可参考。。。。。https://github.com/cliuxinxin/Software-Engineering-at-Google/blob/main/zh/Preface.md

脚本是空的
