### ISSUE TITLE
目录标题建议统一成不带冒号

### ISSUE THREAD

**Issue by fishautumn** [qiangmzsx/Software-Engineering-at-Google#44]
![image](https://user-images.githubusercontent.com/2674795/177948208-01560af5-fcc6-4deb-876c-0186211be712.png)

**Comment by qiangmzsx** [comment]
> ![image](https://user-images.githubusercontent.com/2674795/177948208-01560af5-fcc6-4deb-876c-0186211be712.png)

可以提交PR上来看看呢
