### ISSUE TITLE
请先介绍一下版权问题

### ISSUE THREAD

**Issue by BenLin0** [qiangmzsx/Software-Engineering-at-Google#50]
原英文版是 open source的吗？请澄清一下，因为我在项目里没有看到相关的版权信息。
如果不是的话，参与这个翻译工作，或者共享这个项目给朋友、同事，都是在助长盗版。

书里的信息很有用，谢谢推介。

**Comment by qiangmzsx** [comment]
Software Engineering at Google
by Titus Winters, Tom Manshreck, and Hyrum Wright
Copyright © 2020 Google, LLC. All rights reserved.
Printed in the United States of America.
Published by O’Reilly Media, Inc., 1005 Gravenstein Highway North, Sebastopol, CA 95472.
O’Reilly books may be purchased for educational, business, or sales promotional use. Online editions are
also available for most titles (http://oreilly.com). For more information, contact our corporate/institutional
sales department: 800-998-9938 or corporate@oreilly.com.

本项目仅用于学习，不能作为商业使用。

**Comment by qiangmzsx** [comment]
> 你是如何拿到英文原版的呢？是付钱从 O'Reilly 那里拿到的吗？条款里允许你放在网上让不特定公众来“学习”吗？ 我要知道这个 chain of custody 才好向其它人推介。

这仅仅是个人学习项目，据我所知，很快就会有中文版书籍的出版，那才是值得你大力推介的，现在的版本只不过是给国人提前预热尝鲜。敬请期待更加准确翻译中文版。

**Comment by MiaoDX** [comment]
http://www.oreilly.com.cn/index.php?func=book&isbn=978-7-5198-6470-5

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/8840792/178130584-9b22ed03-97ae-43d8-8523-3469155ba4b7.png">

已出版，京东上也可以直接购买。

也许我们该去问问 oreilly 出版社，他们是如何进行新书翻译的，毕竟目前很多书籍的翻译版本并没有经过足够的 review，导致中文版本质量没有特别好的保证 0.0

**Comment by qiangmzsx** [comment]
> http://www.oreilly.com.cn/index.php?func=book&isbn=978-7-5198-6470-5
> 
> <img alt="image" width="1002" src="https://user-images.githubusercontent.com/8840792/178130584-9b22ed03-97ae-43d8-8523-3469155ba4b7.png">
> 
> 已出版，京东上也可以直接购买。
> 
> 也许我们该去问问 oreilly 出版社，他们是如何进行新书翻译的，毕竟目前很多书籍的翻译版本并没有经过足够的 review，导致中文版本质量没有特别好的保证 0.0

欢迎大家去支持中文版的书籍，我也购买一本阅读对比一下。

**Comment by oe** [comment]
> 

同意, 如果未获得出版商、作者的许可, 即使是非商业行为也是属于盗版, readme 末尾的授权许可就有点讽刺了.
readme 首页没有任何关于版权所有者、出版商、英文原文的信息及链接 也让人费解.

希望译者尊重版权, 尊重他人的劳动成果🙏🏻

**Comment by bougenville** [comment]
本书可以免费在线阅读，请访问谷歌官方链接 https://sre.google

**Comment by oe** [comment]
> 本书可以免费在线阅读，请访问谷歌官方链接 https://sre.google

这和是否能翻译、授权并无关系, 也无法说明本项目的合法性

**Comment by BenLin0** [comment]
> 

I don't see this book in the link you provided. There are 3 books in that site, but none of them is the book of this project.

**Comment by Lutra-Fs** [comment]
refers to https://abseil.io/blog/04222021-swe-book
> We’re very pleased to announce that the “Software Engineering at Google” book (the Flamingo Book) is now freely available electronically under a Creative Commons license.
