### ISSUE TITLE
生成page的workflow介意分享一下吗？

### ISSUE THREAD

**Issue by youngzhu** [qiangmzsx/Software-Engineering-at-Google#52]

**Comment by qiangmzsx** [comment]
> _No description provided._

不太明白，可以详细说说看。

**Comment by jimersylee** [comment]
@qiangmzsx 他想问如何生成从markdown文件发布成在线阅读的那个地址的https://qiangmzsx.github.io/Software-Engineering-at-Google/#/

**Comment by qiangmzsx** [comment]
https://pages.github.com/
查阅这个就好了！
就在seting的page里面。

**Comment by suixinio** [comment]
项目使用的是 docsify ，教程在下面的传送门中。
[传送门](https://docsify.js.org/#/deploy)

github 不需要单独增加 workflow 文件，在 GitHub Pages 配置即可。:)

**Comment by youngzhu** [comment]
> 

没太明白。意思是这里的所有东西，io那个repository里有一份一样的？

**Comment by youngzhu** [comment]
> 项目使用的是 docsify ，教程在下面的传送门中。 [传送门](https://docsify.js.org/#/deploy)
> 
> github 不需要单独增加 workflow 文件，在 GitHub Pages 配置即可。:)


没太明白。意思是这里的所有东西，io那个repository里有一份一样的？

**Comment by qiangmzsx** [comment]
> > 项目使用的是 docsify ，教程在下面的传送门中。 [传送门](https://docsify.js.org/#/deploy)
> > github 不需要单独增加 workflow 文件，在 GitHub Pages 配置即可。:)
> 
> 没太明白。意思是这里的所有东西，io那个repository里有一份一样的？

pages使用的就是仓库的数据。更新仓库就会自动更新pages

**Comment by youngzhu** [comment]
哦，我以为是某个repository（非github.io)的文章可以通过workflow之类的在pages展示
