### ISSUE TITLE
是否可以开启 GitHub Sponsor？

### ISSUE THREAD

**Issue by iwill** [qiangmzsx/Software-Engineering-at-Google#66]
翻译得很好，你们配得上 👍🏿

**Comment by qiangmzsx** [comment]
> 翻译得很好，你们配得上 👍🏿

非常感谢你的认可。我们的项目是开放的、免费的，我们欢迎个人和公司都参与到项目中来，可以为修订出更好的内容。
后续完成修订后我们整理一个参与人员和公司的表格。
