### ISSUE TITLE
chapter 5 有人翻译吗？

### ISSUE THREAD

**Issue by linuxcer** [qiangmzsx/Software-Engineering-at-Google#7]
hi，第五章有人翻译吗？ 怎么报个名

**Comment by qiangmzsx** [comment]
> hi，第五章有人翻译吗？ 怎么报个名

第五章或者第九章可以选择，你看看你选择哪一个呢？

**Comment by linuxcer** [comment]
> > hi，第五章有人翻译吗？ 怎么报个名
> 
> 第五章或者第九章可以选择，你看看你选择哪一个呢？

选第五章

**Comment by qiangmzsx** [comment]
> linuxcer

已经分配好了，在目录中可以看到了。建议与其他章节的格式一样，有中英文的对照模式。

**Comment by linuxcer** [comment]
> 
好的

**Comment by qiangmzsx** [comment]
@linuxcer  第五章进度怎么样了
