### ISSUE TITLE
在一个类中, "public API" 是否应该翻译成「公开 API」而不是「公共 API」

### ISSUE THREAD

**Issue by PentaTea** [qiangmzsx/Software-Engineering-at-Google#84]
在章节 [Test via Public APIs 通过公共API进行测试](https://qiangmzsx.github.io/Software-Engineering-at-Google/#/zh-cn/Chapter-12_Unit_Testing/Chapter-12_Unit_Testing?id=test-via-public-apis-%e9%80%9a%e8%bf%87%e5%85%ac%e5%85%b1api%e8%bf%9b%e8%a1%8c%e6%b5%8b%e8%af%95) 的标题以及下方内容提到的 "public API", 我认为将其翻译为 "公开 API" 会更加准确和恰当。

此处 "public" 强调的是对外部代码的可访问性和可调用性，而不是指某种共享或普遍性。因此，将 "public API" 翻译为「公开 API」更准确地传达了其含义。

**Comment by qiangmzsx** [comment]
> public API

可以的，你可以修改后，提交PR上来。
